stages:
  - test
  - deploy

run_tests:
  image: docker:20.10.16
  stage: deploy
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker build -t testcontainer -f Dockerfile.dev .
  script:
    - docker run testcontainer npm run test

deploy_application:
  image: docker:20.10.16
  stage: deploy
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker build -t testcontainer  .
  script:
    - docker run testcontainer 

